<Project>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AnalysisLevel>latest</AnalysisLevel>
    <AnalysisMode>Recommended</AnalysisMode>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <Version>2.0.0.0</Version>
    <FileVersion>2.0.0.0</FileVersion>
    <InformationalVersion>2.0.0</InformationalVersion>
    <UserSecretsId>spo2sql-modernization-secrets</UserSecretsId>
    <NoWarn>$(NoWarn);CS8618;CS8600;CS8601;CS8602;CS8603;CS8604;CS8625;CS8605;CS8605;CA1416;NU1603;CS0618;CS0649;CA1305;CA1310;CA1311;CA1304;CA1846;CA1862;CA1866;CA5350;CA2201;CA1805</NoWarn>
  </PropertyGroup>
</Project>
